# Project information
site_name: KTracer
site_url: https://annapivetta.github.io/KTracer
site_author: Martinelli Matteo, Pivetta Anna
site_description: >-
  Generate your photorealistic images with this Kotlin written Ray-Tracer. Learn in 5 minutes and
  start having fun!

# Repository
repo_name: AnnaPivetta/KTracer
repo_url: https://github.com/AnnaPivetta/KTracer
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2021 Martinelli Matteo & Pivetta Anna

theme:
  name: null
  custom_dir: material
  palette:
    - primary: teal
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    - scheme: slate
      primary: lime
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode



  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
    repo: fontawesome/brands/github

# Customization
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MatteoMartinelli97